### PR TITLE
Add oauth token fetch

### PR DESCRIPTION
**Pull request by BoraxTheClean**
Address #66 

I will happily make any changes suggested.

Usage
```python3
>>> import twitch
>>> c = twitch.TwitchHelix(client_id='<client_id>',client_secret='<client_secret>')
>>> c.get_oauth()
>>> c.get_streams()
```
## What Changed

Add constants for OAuth Scopes.
Add TwitchOAuthException
Add new method in TwitchHelix to obtain an OAuth2 Token if `client_id` and `client_secret` are present
`flake8` changes applied
`black` run

## What might need to be done

Doc updates

### CODE REVIEW

**Comment by BoraxTheClean** [comment]
Tests added

**Comment by BoraxTheClean** [comment]
I am not sure what I can do to make the codecov check pass. I am having trouble navigating that UI to figure out where I am going wrong. I'd appreciate any guidance on this and the PR as a whole @tsifrer

**Comment by goldbattle** [comment]
This solved my issue and saved me from going through the oauth processes manually.
Thanks so much for this, I hope this gets merged into master!

**Comment by BoraxTheClean** [comment]
The code coverage issue should be resolved now.

**Review by tsifrer — APPROVED** [review]
Thank you for this! I'm so sorry for not being able to review this sooner.

**Comment by tsifrer** [comment]
@BoraxTheClean May I just ask why are `client_secret=None, scopes=None` parameters on the TwitchHelix class and stored on the class, rather than being parameters to `get_oauth` method? These params are only used in that function so I'm not sure why they'd need to be stored on the class?

**Comment by tsifrer** [comment]
@BoraxTheClean NEVERMIND 🤦  It's too early in the morning for me it seems. I re-read the code and makes total sense now. Thanks again for this.

**Comment by BoraxTheClean** [comment]
Thanks for the merge @tsifrer! This was my first Open Source contribution!

**Pull request merged**
